language: python

python:
  - 2.7

before_script:
  - psql -c 'create database psycopg2_test;' -U postgres

install:
  - python setup.py install

script: make check

#build_image: drydock/u14pytpls:prod
